
apiVersion: boom.caos.ch/v1beta2
kind: Toolset
metadata:
  name: caos
  namespace: caos-system
spec:
  boomVersion: v0.28.5
  postApply: {}
  metricCollection:
    deploy: true
  logCollection:
    deploy: true
  nodeMetricsExporter:
    deploy: true
  systemdMetricsExporter:
    deploy: true
  monitoring:
    deploy: true
  apiGateway:
    deploy: true
    replicaCount: 3
  kubeMetricsExporter:
    deploy: true
  reconciling:
    deploy: true
  metricsPersisting:
    deploy: true
  logsPersisting:
    deploy: true
